#!/bin/sh

command="$0"
subcommand="$1"
case $subcommand in
    "-h" | "--help")
	echo "Usage: $command <subcommand> [arguments]"
	echo ""
	echo "Subcommands:"
	echo "    update-lockfile   Update lockfile"
	echo "    build             Build the project"
	echo "    [no args]         Run the project"
	echo ""
	;;
    "update-lockfile")
	LOCK_FILE=${CHANNEL_FILE:-channels.lock.scm}
	CHANNEL_FILE=${CHANNEL_FILE:-channels.scm}
	tmplock="$(mktemp)";
	guix time-machine -C "$CHANNEL_FILE" -- describe -f channels >"$tmplock" && \
	    # only overrwrite if succeeded
	    cat "$tmplock" > "$LOCK_FILE";
	rm -f "$tmplock"
	;;
    "build")
	SOURCE_FILE=${SOURCE_FILE:-scream.scm}
	TRANSPILED_FILE=${TRANSPILED_FILE:-out.c}
	OUT_FILE=${OUT_FILE:-out}
	guile "$SOURCE_FILE" && gcc "$TRANSPILED_FILE" -o "$OUT_FILE"
	;;
    *)
	"$command" build && "./${OUT_FILE:-out}" "$@"
	;;
esac
